name: Step Completion Workflow

on:
  pull_request:
    branches:
      - main

permissions:
    contents: write
    pull-requests: write
    repository-projects: write

jobs:
  check-solution:
    runs-on: ubuntu-latest
    outputs:
      assessment: ${{ steps.solution.outputs.assessment }}
      reason: ${{ steps.solution.outputs.reason }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Solution
        id: solution
        uses: andrewdmaclean-work/action-check-file@main
        with:
          step: ".github/steps/1-add-hello.md"
          submission: "hello-world.md"
          solution: ".github/solutions/1-solution-prompt.md"
          webhook: ${{ vars.WEBHOOK_URL }}
          accountsid: ${{ vars.ACCOUNT_SID }}
          authtoken: ${{ secrets.AUTH_TOKEN }}
  check-variables:
    runs-on: ubuntu-latest
    needs: check-solution
    steps:
      - name: Check if Variables are Set
        run: echo "Assessment is ${{ needs.check-solution.outputs.assessment }}"
  update-step:
    runs-on: ubuntu-latest
    needs: check-solution
    if: needs.check-solution.outputs.assessment == 'correct'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update to step 2
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: main

  comment-on-pr:
    runs-on: ubuntu-latest
    needs: check-solution
    steps:
      - name: Success Comment
        if: needs.check-solution.outputs.assessment == 'correct'
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
            -d '{"body":"🎉 Congratulations! You successfully completed step 1. Go back to the README in the main branch to continue."}'

      - name: Try Again Comment
        if: needs.check-solution.outputs.assessment != 'correct'
        run: |
          curl -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
            -d '{"body":"🚫 The solution did not pass the validation check. Please try again. **Reason:** ${{ needs.check-solution.outputs.reason }}"}'

  merge-pr:
    runs-on: ubuntu-latest
    needs: check-solution
    if: needs.check-solution.outputs.assessment == 'correct'
    steps:
      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin --repo ${{ github.repository }}
